<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string></string>
	</array>
	<key>firstLineMatch</key>
	<string>^(\&lt;\d\&gt;)?\[\s*[\d.]+\]\s+Initializing</string>
	<key>name</key>
	<string>dmesg</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>No</string>
			<key>match</key>
			<string>^(\&lt;\d\&gt;)?\[\s*[\d.]+\]</string>
			<key>name</key>
			<string>entity.name.text.dmesg</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Error</string>
			<key>match</key>
			<string>[Ff]ailed|[Ii]nvalid|[Ee]rror|[Ww]rong|WARN|ERROR</string>
			<key>name</key>
			<string>keyword.text.dmesg</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Important</string>
			<key>match</key>
			<string>BIOS|EFI|[Mm]em[^\s]*|ACPI|pci[^\s]*|PCI|RAM|[Bb]oot[^\s]*|GPIO[^\s]*|CPU|TCP|NET|PPP|Bluetooth|ehci[^\s]*|(([u]sb)|USB)[^\s]*|[Hh]ub|[Ii]nput[^\s]*|system|[Dd]evice[^\s]*|yaffs|[Ii]nit[^\s]*</string>
			<key>name</key>
			<string>string.text.dmesg</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Note</string>
			<key>match</key>
			<string>FIXME|0x</string>
			<key>name</key>
			<string>support.function.text.dmesg</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Action</string>
			<key>match</key>
			<string>Initializing|Registered|Ignoring|Disabling|mapping</string>
			<key>name</key>
			<string>constant.support.text.dmesg</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Number</string>
			<key>match</key>
			<string>[\dabcdefABCDEF]{16}|\d{4}:\d{2}:[\dabcdefABCDEF]{2}.\d:|-?[\dabcdefABCDEF]{4,16}|(?&lt;=(0x))[\dabcdefABCDEF]+</string>
			<key>name</key>
			<string>constant.numberic.text.dmesg</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.dmesg</string>
	<key>uuid</key>
	<string>2345756b-e633-4233-9772-d5c73f7ef27e</string>
</dict>
</plist>
