<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string></string>
	</array>
	<key>firstLineMatch</key>
	<string>^[IWDE]/</string>
	<key>name</key>
	<string>logcat</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Information</string>
			<key>match</key>
			<string>^I/\w+</string>
			<key>name</key>
			<string>entity.name.text.logcat</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Warning</string>
			<key>match</key>
			<string>^W/\w+</string>
			<key>name</key>
			<string>constant.support.text.logcat</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Debug</string>
			<key>match</key>
			<string>^D/\w+</string>
			<key>name</key>
			<string>support.function.text.logcat</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Error</string>
			<key>match</key>
			<string>^E/\w+|error(\scode\s+=\s+\d+)*|(\w)*Exception|at\s+|.err|died|denied</string>
			<key>name</key>
			<string>keyword.text.logcat</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>No</string>
			<key>match</key>
			<string>\(\s*\d+\)</string>
			<key>name</key>
			<string>storage.modifier.text.logcat</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Action</string>
			<key>match</key>
			<string>Initializing|Registered|Ignoring|Disabling|mapping|Setting</string>
			<key>name</key>
			<string>constant.support.text.logcat</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.logcat</string>
	<key>uuid</key>
	<string>d5cfeeec-a040-454b-ba47-6a08db263ac6</string>
</dict>
</plist>
